-- Moodle 4.4 core tables (subset) generated from official install.xml (MOODLE_404_STABLE)
-- Chỉ dùng để chạy thử cục bộ; trên máy thật đây là CSDL Moodle có sẵn.
CREATE DATABASE IF NOT EXISTS moodle CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE moodle;
CREATE TABLE IF NOT EXISTS `mdl_course` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `category` BIGINT NOT NULL DEFAULT '0',
  `sortorder` BIGINT NOT NULL DEFAULT '0',
  `fullname` VARCHAR(254) NOT NULL DEFAULT '',
  `shortname` VARCHAR(255) NOT NULL DEFAULT '',
  `idnumber` VARCHAR(100) NOT NULL DEFAULT '',
  `summary` LONGTEXT,
  `summaryformat` TINYINT NOT NULL DEFAULT '0',
  `format` VARCHAR(21) NOT NULL DEFAULT 'topics',
  `showgrades` TINYINT NOT NULL DEFAULT '1',
  `newsitems` INT NOT NULL DEFAULT '1',
  `startdate` BIGINT NOT NULL DEFAULT '0',
  `enddate` BIGINT NOT NULL DEFAULT '0',
  `relativedatesmode` TINYINT NOT NULL DEFAULT '0',
  `marker` BIGINT NOT NULL DEFAULT '0',
  `maxbytes` BIGINT NOT NULL DEFAULT '0',
  `legacyfiles` SMALLINT NOT NULL DEFAULT '0',
  `showreports` SMALLINT NOT NULL DEFAULT '0',
  `visible` TINYINT NOT NULL DEFAULT '1',
  `visibleold` TINYINT NOT NULL DEFAULT '1',
  `downloadcontent` TINYINT,
  `groupmode` SMALLINT NOT NULL DEFAULT '0',
  `groupmodeforce` SMALLINT NOT NULL DEFAULT '0',
  `defaultgroupingid` BIGINT NOT NULL DEFAULT '0',
  `lang` VARCHAR(30) NOT NULL DEFAULT '',
  `calendartype` VARCHAR(30) NOT NULL DEFAULT '',
  `theme` VARCHAR(50) NOT NULL DEFAULT '',
  `timecreated` BIGINT NOT NULL DEFAULT '0',
  `timemodified` BIGINT NOT NULL DEFAULT '0',
  `requested` TINYINT NOT NULL DEFAULT '0',
  `enablecompletion` TINYINT NOT NULL DEFAULT '0',
  `completionnotify` TINYINT NOT NULL DEFAULT '0',
  `cacherev` BIGINT NOT NULL DEFAULT '0',
  `originalcourseid` BIGINT,
  `showactivitydates` TINYINT NOT NULL DEFAULT '0',
  `showcompletionconditions` TINYINT,
  `pdfexportfont` VARCHAR(50),
  PRIMARY KEY (`id`),
  KEY `mdl_course_category` (`category`),
  KEY `mdl_course_idnumber` (`idnumber`),
  KEY `mdl_course_shortname` (`shortname`),
  KEY `mdl_course_sortorder` (`sortorder`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mdl_enrol` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `enrol` VARCHAR(20) NOT NULL DEFAULT '',
  `status` BIGINT NOT NULL DEFAULT '0',
  `courseid` BIGINT NOT NULL,
  `sortorder` BIGINT NOT NULL DEFAULT '0',
  `name` VARCHAR(255),
  `enrolperiod` BIGINT DEFAULT '0',
  `enrolstartdate` BIGINT DEFAULT '0',
  `enrolenddate` BIGINT DEFAULT '0',
  `expirynotify` TINYINT DEFAULT '0',
  `expirythreshold` BIGINT DEFAULT '0',
  `notifyall` TINYINT DEFAULT '0',
  `password` VARCHAR(50),
  `cost` VARCHAR(20),
  `currency` VARCHAR(3),
  `roleid` BIGINT DEFAULT '0',
  `customint1` BIGINT,
  `customint2` BIGINT,
  `customint3` BIGINT,
  `customint4` BIGINT,
  `customint5` BIGINT,
  `customint6` BIGINT,
  `customint7` BIGINT,
  `customint8` BIGINT,
  `customchar1` VARCHAR(255),
  `customchar2` VARCHAR(255),
  `customchar3` VARCHAR(1333),
  `customdec1` DECIMAL(12,7),
  `customdec2` DECIMAL(12,7),
  `customtext1` LONGTEXT,
  `customtext2` LONGTEXT,
  `customtext3` LONGTEXT,
  `customtext4` LONGTEXT,
  `timecreated` BIGINT NOT NULL DEFAULT '0',
  `timemodified` BIGINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `mdl_enrol_enrol` (`enrol`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mdl_user_enrolments` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` BIGINT NOT NULL DEFAULT '0',
  `enrolid` BIGINT NOT NULL,
  `userid` BIGINT NOT NULL,
  `timestart` BIGINT NOT NULL DEFAULT '0',
  `timeend` BIGINT NOT NULL DEFAULT '2147483647',
  `modifierid` BIGINT NOT NULL DEFAULT '0',
  `timecreated` BIGINT NOT NULL DEFAULT '0',
  `timemodified` BIGINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `mdl_user_enrol_enrolid-userid` (`enrolid`,`userid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mdl_user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `auth` VARCHAR(20) NOT NULL DEFAULT 'manual',
  `confirmed` TINYINT NOT NULL DEFAULT '0',
  `policyagreed` TINYINT NOT NULL DEFAULT '0',
  `deleted` TINYINT NOT NULL DEFAULT '0',
  `suspended` TINYINT NOT NULL DEFAULT '0',
  `mnethostid` BIGINT NOT NULL DEFAULT '0',
  `username` VARCHAR(100) NOT NULL DEFAULT '',
  `password` VARCHAR(255) NOT NULL DEFAULT '',
  `idnumber` VARCHAR(255) NOT NULL DEFAULT '',
  `firstname` VARCHAR(100) NOT NULL DEFAULT '',
  `lastname` VARCHAR(100) NOT NULL DEFAULT '',
  `email` VARCHAR(100) NOT NULL DEFAULT '',
  `emailstop` TINYINT NOT NULL DEFAULT '0',
  `phone1` VARCHAR(20) NOT NULL DEFAULT '',
  `phone2` VARCHAR(20) NOT NULL DEFAULT '',
  `institution` VARCHAR(255) NOT NULL DEFAULT '',
  `department` VARCHAR(255) NOT NULL DEFAULT '',
  `address` VARCHAR(255) NOT NULL DEFAULT '',
  `city` VARCHAR(120) NOT NULL DEFAULT '',
  `country` VARCHAR(2) NOT NULL DEFAULT '',
  `lang` VARCHAR(30) NOT NULL DEFAULT 'en',
  `calendartype` VARCHAR(30) NOT NULL DEFAULT 'gregorian',
  `theme` VARCHAR(50) NOT NULL DEFAULT '',
  `timezone` VARCHAR(100) NOT NULL DEFAULT '99',
  `firstaccess` BIGINT NOT NULL DEFAULT '0',
  `lastaccess` BIGINT NOT NULL DEFAULT '0',
  `lastlogin` BIGINT NOT NULL DEFAULT '0',
  `currentlogin` BIGINT NOT NULL DEFAULT '0',
  `lastip` VARCHAR(45) NOT NULL DEFAULT '',
  `secret` VARCHAR(15) NOT NULL DEFAULT '',
  `picture` BIGINT NOT NULL DEFAULT '0',
  `description` LONGTEXT,
  `descriptionformat` TINYINT NOT NULL DEFAULT '1',
  `mailformat` TINYINT NOT NULL DEFAULT '1',
  `maildigest` TINYINT NOT NULL DEFAULT '0',
  `maildisplay` TINYINT NOT NULL DEFAULT '2',
  `autosubscribe` TINYINT NOT NULL DEFAULT '1',
  `trackforums` TINYINT NOT NULL DEFAULT '0',
  `timecreated` BIGINT NOT NULL DEFAULT '0',
  `timemodified` BIGINT NOT NULL DEFAULT '0',
  `trustbitmask` BIGINT NOT NULL DEFAULT '0',
  `imagealt` VARCHAR(255),
  `lastnamephonetic` VARCHAR(255),
  `firstnamephonetic` VARCHAR(255),
  `middlename` VARCHAR(255),
  `alternatename` VARCHAR(255),
  `moodlenetprofile` VARCHAR(255),
  PRIMARY KEY (`id`),
  UNIQUE KEY `mdl_user_username` (`mnethostid`,`username`),
  KEY `mdl_user_deleted` (`deleted`),
  KEY `mdl_user_confirmed` (`confirmed`),
  KEY `mdl_user_firstname` (`firstname`),
  KEY `mdl_user_lastname` (`lastname`),
  KEY `mdl_user_city` (`city`),
  KEY `mdl_user_country` (`country`),
  KEY `mdl_user_lastaccess` (`lastaccess`),
  KEY `mdl_user_email` (`email`),
  KEY `mdl_user_auth` (`auth`),
  KEY `mdl_user_idnumber` (`idnumber`),
  KEY `mdl_user_firstnamephonetic` (`firstnamephonetic`),
  KEY `mdl_user_lastnamephonetic` (`lastnamephonetic`),
  KEY `mdl_user_middlename` (`middlename`),
  KEY `mdl_user_alternatename` (`alternatename`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mdl_role` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `shortname` VARCHAR(100) NOT NULL DEFAULT '',
  `description` LONGTEXT NOT NULL,
  `sortorder` BIGINT NOT NULL DEFAULT '0',
  `archetype` VARCHAR(30) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `mdl_role_sortorder` (`sortorder`),
  UNIQUE KEY `mdl_role_shortname` (`shortname`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mdl_context` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `contextlevel` BIGINT NOT NULL DEFAULT '0',
  `instanceid` BIGINT NOT NULL DEFAULT '0',
  `path` VARCHAR(255),
  `depth` TINYINT NOT NULL DEFAULT '0',
  `locked` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `mdl_context_contextlevel-instanc` (`contextlevel`,`instanceid`),
  KEY `mdl_context_instanceid` (`instanceid`),
  KEY `mdl_context_path` (`path`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mdl_role_assignments` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `roleid` BIGINT NOT NULL DEFAULT '0',
  `contextid` BIGINT NOT NULL DEFAULT '0',
  `userid` BIGINT NOT NULL DEFAULT '0',
  `timemodified` BIGINT NOT NULL DEFAULT '0',
  `modifierid` BIGINT NOT NULL DEFAULT '0',
  `component` VARCHAR(100) NOT NULL DEFAULT '',
  `itemid` BIGINT NOT NULL DEFAULT '0',
  `sortorder` BIGINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `mdl_role_assig_sortorder` (`sortorder`),
  KEY `mdl_role_assig_rolecontext` (`roleid`,`contextid`),
  KEY `mdl_role_assig_usercontextrole` (`userid`,`contextid`,`roleid`),
  KEY `mdl_role_assig_component-itemid-use` (`component`,`itemid`,`userid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mdl_question_categories` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `contextid` BIGINT NOT NULL DEFAULT '0',
  `info` LONGTEXT NOT NULL,
  `infoformat` TINYINT NOT NULL DEFAULT '0',
  `stamp` VARCHAR(255) NOT NULL DEFAULT '',
  `parent` BIGINT NOT NULL DEFAULT '0',
  `sortorder` BIGINT NOT NULL DEFAULT '999',
  `idnumber` VARCHAR(100),
  PRIMARY KEY (`id`),
  KEY `mdl_question_c_contextid` (`contextid`),
  UNIQUE KEY `mdl_question_c_contextidstamp` (`contextid`,`stamp`),
  UNIQUE KEY `mdl_question_c_contextididnumber` (`contextid`,`idnumber`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mdl_question` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `parent` BIGINT NOT NULL DEFAULT '0',
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `questiontext` LONGTEXT NOT NULL,
  `questiontextformat` TINYINT NOT NULL DEFAULT '0',
  `generalfeedback` LONGTEXT NOT NULL,
  `generalfeedbackformat` TINYINT NOT NULL DEFAULT '0',
  `defaultmark` DECIMAL(12,7) NOT NULL DEFAULT '1',
  `penalty` DECIMAL(12,7) NOT NULL DEFAULT '0.3333333',
  `qtype` VARCHAR(20) NOT NULL DEFAULT '',
  `length` BIGINT NOT NULL DEFAULT '1',
  `stamp` VARCHAR(255) NOT NULL DEFAULT '',
  `timecreated` BIGINT NOT NULL DEFAULT '0',
  `timemodified` BIGINT NOT NULL DEFAULT '0',
  `createdby` BIGINT,
  `modifiedby` BIGINT,
  PRIMARY KEY (`id`),
  KEY `mdl_question_qtype` (`qtype`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mdl_question_bank_entries` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `questioncategoryid` BIGINT NOT NULL DEFAULT '0',
  `idnumber` VARCHAR(100),
  `ownerid` BIGINT,
  PRIMARY KEY (`id`),
  UNIQUE KEY `mdl_question_b_categoryidnumber` (`questioncategoryid`,`idnumber`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mdl_question_versions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `questionbankentryid` BIGINT NOT NULL DEFAULT '0',
  `version` BIGINT NOT NULL DEFAULT '1',
  `questionid` BIGINT NOT NULL DEFAULT '0',
  `status` VARCHAR(10) NOT NULL DEFAULT 'ready',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mdl_question_references` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `usingcontextid` BIGINT NOT NULL DEFAULT '0',
  `component` VARCHAR(100),
  `questionarea` VARCHAR(50),
  `itemid` BIGINT,
  `questionbankentryid` BIGINT NOT NULL DEFAULT '0',
  `version` BIGINT,
  PRIMARY KEY (`id`),
  UNIQUE KEY `mdl_question_r_context-component-ar` (`usingcontextid`,`component`,`questionarea`,`itemid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mdl_question_answers` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `question` BIGINT NOT NULL DEFAULT '0',
  `answer` LONGTEXT NOT NULL,
  `answerformat` TINYINT NOT NULL DEFAULT '0',
  `fraction` DECIMAL(12,7) NOT NULL DEFAULT '0',
  `feedback` LONGTEXT NOT NULL,
  `feedbackformat` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mdl_question_usages` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `contextid` BIGINT NOT NULL,
  `component` VARCHAR(255) NOT NULL DEFAULT '',
  `preferredbehaviour` VARCHAR(32) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mdl_question_attempts` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `questionusageid` BIGINT NOT NULL,
  `slot` BIGINT NOT NULL,
  `behaviour` VARCHAR(32) NOT NULL DEFAULT '',
  `questionid` BIGINT NOT NULL,
  `variant` BIGINT NOT NULL DEFAULT '1',
  `maxmark` DECIMAL(12,7) NOT NULL,
  `minfraction` DECIMAL(12,7) NOT NULL,
  `maxfraction` DECIMAL(12,7) NOT NULL DEFAULT '1',
  `flagged` TINYINT NOT NULL DEFAULT '0',
  `questionsummary` LONGTEXT,
  `rightanswer` LONGTEXT,
  `responsesummary` LONGTEXT,
  `timemodified` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `mdl_question_a_questionusageid-slot` (`questionusageid`,`slot`),
  KEY `mdl_question_a_behaviour` (`behaviour`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mdl_question_attempt_steps` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `questionattemptid` BIGINT NOT NULL,
  `sequencenumber` BIGINT NOT NULL,
  `state` VARCHAR(13) NOT NULL DEFAULT '',
  `fraction` DECIMAL(12,7),
  `timecreated` BIGINT NOT NULL,
  `userid` BIGINT,
  PRIMARY KEY (`id`),
  UNIQUE KEY `mdl_question_a_questionattemptid-se` (`questionattemptid`,`sequencenumber`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mdl_question_attempt_step_data` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `attemptstepid` BIGINT NOT NULL,
  `name` VARCHAR(32) NOT NULL DEFAULT '',
  `value` LONGTEXT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mdl_quiz` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `course` BIGINT NOT NULL DEFAULT '0',
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `intro` LONGTEXT NOT NULL,
  `introformat` SMALLINT NOT NULL DEFAULT '0',
  `timeopen` BIGINT NOT NULL DEFAULT '0',
  `timeclose` BIGINT NOT NULL DEFAULT '0',
  `timelimit` BIGINT NOT NULL DEFAULT '0',
  `overduehandling` VARCHAR(16) NOT NULL DEFAULT 'autoabandon',
  `graceperiod` BIGINT NOT NULL DEFAULT '0',
  `preferredbehaviour` VARCHAR(32) NOT NULL DEFAULT '',
  `canredoquestions` SMALLINT NOT NULL DEFAULT '0',
  `attempts` INT NOT NULL DEFAULT '0',
  `attemptonlast` SMALLINT NOT NULL DEFAULT '0',
  `grademethod` SMALLINT NOT NULL DEFAULT '1',
  `decimalpoints` SMALLINT NOT NULL DEFAULT '2',
  `questiondecimalpoints` SMALLINT NOT NULL DEFAULT '-1',
  `reviewattempt` INT NOT NULL DEFAULT '0',
  `reviewcorrectness` INT NOT NULL DEFAULT '0',
  `reviewmaxmarks` INT NOT NULL DEFAULT '0',
  `reviewmarks` INT NOT NULL DEFAULT '0',
  `reviewspecificfeedback` INT NOT NULL DEFAULT '0',
  `reviewgeneralfeedback` INT NOT NULL DEFAULT '0',
  `reviewrightanswer` INT NOT NULL DEFAULT '0',
  `reviewoverallfeedback` INT NOT NULL DEFAULT '0',
  `questionsperpage` BIGINT NOT NULL DEFAULT '0',
  `navmethod` VARCHAR(16) NOT NULL DEFAULT 'free',
  `shuffleanswers` SMALLINT NOT NULL DEFAULT '0',
  `sumgrades` DECIMAL(10,5) NOT NULL DEFAULT '0',
  `grade` DECIMAL(10,5) NOT NULL DEFAULT '0',
  `timecreated` BIGINT NOT NULL DEFAULT '0',
  `timemodified` BIGINT NOT NULL DEFAULT '0',
  `password` VARCHAR(255) NOT NULL DEFAULT '',
  `subnet` VARCHAR(255) NOT NULL DEFAULT '',
  `browsersecurity` VARCHAR(32) NOT NULL DEFAULT '',
  `delay1` BIGINT NOT NULL DEFAULT '0',
  `delay2` BIGINT NOT NULL DEFAULT '0',
  `showuserpicture` SMALLINT NOT NULL DEFAULT '0',
  `showblocks` SMALLINT NOT NULL DEFAULT '0',
  `completionattemptsexhausted` TINYINT DEFAULT '0',
  `completionminattempts` BIGINT NOT NULL DEFAULT '0',
  `allowofflineattempts` TINYINT DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `mdl_quiz_course` (`course`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mdl_quiz_slots` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `slot` BIGINT NOT NULL,
  `quizid` BIGINT NOT NULL DEFAULT '0',
  `page` BIGINT NOT NULL,
  `displaynumber` VARCHAR(16),
  `requireprevious` SMALLINT NOT NULL DEFAULT '0',
  `maxmark` DECIMAL(12,7) NOT NULL DEFAULT '0',
  `quizgradeitemid` BIGINT,
  PRIMARY KEY (`id`),
  UNIQUE KEY `mdl_quiz_slots_quizid-slot` (`quizid`,`slot`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mdl_quiz_attempts` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `quiz` BIGINT NOT NULL DEFAULT '0',
  `userid` BIGINT NOT NULL DEFAULT '0',
  `attempt` INT NOT NULL DEFAULT '0',
  `uniqueid` BIGINT NOT NULL DEFAULT '0',
  `layout` LONGTEXT NOT NULL,
  `currentpage` BIGINT NOT NULL DEFAULT '0',
  `preview` SMALLINT NOT NULL DEFAULT '0',
  `state` VARCHAR(16) NOT NULL DEFAULT 'inprogress',
  `timestart` BIGINT NOT NULL DEFAULT '0',
  `timefinish` BIGINT NOT NULL DEFAULT '0',
  `timemodified` BIGINT NOT NULL DEFAULT '0',
  `timemodifiedoffline` BIGINT NOT NULL DEFAULT '0',
  `timecheckstate` BIGINT DEFAULT '0',
  `sumgrades` DECIMAL(10,5),
  `gradednotificationsenttime` BIGINT,
  PRIMARY KEY (`id`),
  UNIQUE KEY `mdl_quiz_attem_quiz-userid-attempt` (`quiz`,`userid`,`attempt`),
  KEY `mdl_quiz_attem_state-timecheckstate` (`state`,`timecheckstate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mdl_quiz_grades` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `quiz` BIGINT NOT NULL DEFAULT '0',
  `userid` BIGINT NOT NULL DEFAULT '0',
  `grade` DECIMAL(10,5) NOT NULL DEFAULT '0',
  `timemodified` BIGINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `mdl_quiz_grade_userid` (`userid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mdl_qtype_multichoice_options` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `questionid` BIGINT NOT NULL DEFAULT '0',
  `layout` SMALLINT NOT NULL DEFAULT '0',
  `single` SMALLINT NOT NULL DEFAULT '0',
  `shuffleanswers` SMALLINT NOT NULL DEFAULT '1',
  `correctfeedback` LONGTEXT NOT NULL,
  `correctfeedbackformat` TINYINT NOT NULL DEFAULT '0',
  `partiallycorrectfeedback` LONGTEXT NOT NULL,
  `partiallycorrectfeedbackformat` TINYINT NOT NULL DEFAULT '0',
  `incorrectfeedback` LONGTEXT NOT NULL,
  `incorrectfeedbackformat` TINYINT NOT NULL DEFAULT '0',
  `answernumbering` VARCHAR(10) NOT NULL DEFAULT 'abc',
  `shownumcorrect` TINYINT NOT NULL DEFAULT '0',
  `showstandardinstruction` TINYINT NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Plugin Offline Quiz (mod_offlinequiz v4.5.4): bài thi giấy – Moodle sinh đề/phiếu, nhận diện phiếu quét và chấm
CREATE TABLE IF NOT EXISTS `mdl_offlinequiz` (
  `id` bigint(10) NOT NULL AUTO_INCREMENT,
  `course` bigint(10) NOT NULL DEFAULT 0,
  `name` varchar(255) NOT NULL DEFAULT '',
  `intro` longtext NOT NULL,
  `introformat` smallint(4) NOT NULL DEFAULT 0,
  `pdfintro` longtext DEFAULT NULL,
  `timeopen` bigint(10) NOT NULL DEFAULT 0,
  `timeclose` bigint(10) NOT NULL DEFAULT 0,
  `time` bigint(10) NOT NULL DEFAULT 0,
  `grade` decimal(10,5) NOT NULL DEFAULT 0.00000,
  `participantsusage` tinyint(1) DEFAULT 1,
  `numgroups` bigint(10) NOT NULL DEFAULT 2,
  `decimalpoints` smallint(4) NOT NULL DEFAULT 2,
  `review` bigint(10) NOT NULL DEFAULT 0,
  `questionsperpage` bigint(10) NOT NULL DEFAULT 0,
  `docscreated` smallint(4) NOT NULL DEFAULT 0,
  `shufflequestions` smallint(4) NOT NULL DEFAULT 0,
  `shuffleanswers` smallint(4) NOT NULL DEFAULT 0,
  `printstudycodefield` smallint(4) NOT NULL DEFAULT 1,
  `pdffont` varchar(255) DEFAULT NULL,
  `papergray` bigint(10) NOT NULL DEFAULT 650,
  `fontsize` smallint(4) NOT NULL DEFAULT 10,
  `timecreated` bigint(10) NOT NULL DEFAULT 0,
  `showquestioninfo` smallint(4) NOT NULL DEFAULT 0,
  `timemodified` bigint(10) NOT NULL DEFAULT 0,
  `fileformat` smallint(4) NOT NULL DEFAULT 0,
  `showgrades` smallint(4) NOT NULL DEFAULT 0,
  `showtutorial` smallint(4) NOT NULL DEFAULT 0,
  `id_digits` smallint(4) DEFAULT NULL,
  `disableimgnewlines` smallint(4) NOT NULL DEFAULT 0,
  `algorithmversion` bigint(10) DEFAULT 0,
  `experimentalevaluation` smallint(4) NOT NULL DEFAULT 0,
  `completionpass` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `mdl_offl_cou_ix` (`course`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mdl_offlinequiz_groups` (
  `id` bigint(10) NOT NULL AUTO_INCREMENT,
  `offlinequizid` bigint(10) NOT NULL,
  `groupnumber` smallint(4) NOT NULL DEFAULT 0,
  `sumgrades` decimal(10,5) NOT NULL DEFAULT 0.00000,
  `numberofpages` smallint(4) NOT NULL DEFAULT 0,
  `templateusageid` bigint(10) NOT NULL DEFAULT 0,
  `questionfilename` varchar(1000) DEFAULT NULL,
  `answerfilename` varchar(1000) DEFAULT NULL,
  `correctionfilename` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `mdl_offlgrou_off_ix` (`offlinequizid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mdl_offlinequiz_results` (
  `id` bigint(10) NOT NULL AUTO_INCREMENT,
  `offlinequizid` bigint(10) NOT NULL,
  `offlinegroupid` bigint(10) NOT NULL,
  `userid` bigint(10) NOT NULL,
  `sumgrades` decimal(10,5) DEFAULT NULL,
  `usageid` bigint(10) NOT NULL,
  `teacherid` bigint(10) NOT NULL,
  `attendant` varchar(255) NOT NULL DEFAULT '',
  `status` varchar(255) NOT NULL DEFAULT '',
  `timestart` bigint(10) NOT NULL DEFAULT 0,
  `timefinish` bigint(10) DEFAULT 0,
  `timemodified` bigint(10) NOT NULL DEFAULT 0,
  `preview` smallint(3) DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `mdl_offlresu_use_ix` (`userid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
